# Generated by Django 4.2.6 on 2023-11-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
