# Generated by Django 4.2.6 on 2023-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsupport',
            name='file_upload',
            field=models.FileField(null=True, upload_to='contact/submissions/documents/'),
        ),
    ]
