# Generated by Django 4.2.6 on 2023-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactsupport_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupport',
            name='file_upload',
            field=models.FileField(null=True, upload_to='contact/submissions/documents/%Y/%m/%d'),
        ),
    ]
